os: linux
dist: xenial
sudo: required
language: python
cache: pip

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server

python:
- '3.6'
- '3.7'
- '3.8'

script:
- pip freeze | xargs pip uninstall -y
- make install-minimal
- make test-minimal && mv .coverage .coverage.minimal

- make install
- make lint
- make test && mv .coverage .coverage.full

- ./tests/check_tag.py
- ls -lha
- pip freeze

after_success:
- coverage combine
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: pypi
  user: __token__
  password:
    secure: "SyYYbQAQS422ZiN0hSzrUj1bT+YyHVBhkow/f2sbsFMYH0qdtovgMoigNNEt45eddLldzfLFHux8Mk2UYRKn7lEnDagq1YYEsb1PsV57Eg+GynRZAcxPynezz7IFx/vwae3F1H85J5c/p5Kwh6o5JTiNgN041K3kjMIPQs2wZwly9LqHwHHncTWKt81P1zOq+kPN4/RiAEdEZOsknw256fBiOXSeW4E9dixrAY6OTlRGJ1MoSQfd8xVmmTV4cxOLznPf3mm7nquDOarzp6t+db/WBc3uozAVZzL7jdlBgrzHaQ/j1a/h6HT9bxfBFZMmpbZXnFQldXY2HRIkVo+zLXA9FgBLP0gnB1bw0JovUXbgknVSTjFhmT4KZS2Z0nZcpCp4UjSTYFV3U+aFmipDcnpKv+wndS8fkQUONIIsxHMpBJ4fpuN5TXLbB/EVsPMiMUqOkeYTW27wn/Y5msMwklnAhWEPuANE0Yy25dyjcf+FFi06bkRgBIAEaGd4eiSZFp5At3DSDhhKu1UpBneuxL8tXYM/odIu/cM4fMV7SjRd6MWn8YkUwue9GqGiK7R6UHhIYrY9X7zVzQc7u0UFQENMyHT4KpANH5xvlST8NkkrELXz84E4eX/+q8Zw++HRyPE3QcvZnkx3nu5Y/pwALq7rJQslkp9CxRn0yPnILes="
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.7
