language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server

matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: required

script:
- pip freeze | xargs pip uninstall -y
- make install-minimal
- make test-minimal && mv .coverage .coverage.minimal

- make install
- make lint
- make test && mv .coverage .coverage.full

- ./tests/check_tag.py
- ls -lha
- pip freeze

after_success:
- coverage combine
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: pypi
  user: samuelcolvin
  password:
    secure: "oi8zNlSmS410e2rmA/qNILWVSJRFK5eYuFtlLicAzhlWdPOi6GuCLqfSP4XL7YtPLXnDaeUQ1EKGIkoKwYzPG7YoFfHnCC9dgm7zVIFqu26da30/+cRcFJQWfMG/BY5Gsw1sJAlGUF6E0vkMggixakaJCQy18Tk7//7DhF5nDpRuQRJF883JjRP4HiIteh+Yx6OVhdERnuP5NpIvbTFUjcUeiv3kkMXO3IM9s9OY9OevTGKL/ZxKjhMB+9L3QcfzR9piPnTEQ4+xKGMF8gglOeFSBECnruuzVgKlEGHrIos5v34QcWKNTNyOKcgEmku39VF9T29LuvoFwIrHjpOBtNpWfAiSvNiqpxKP0isAX4LxxRrfWo4EJjJqvCkz66X2yyno1dpc06UwrG1ISbuatf5bfdRee2rNGiS5AyK9r/3YDbnzDD8JXGHtr78zIMId47TXyqlteN0Im6/1ahWHsJ43PewdmRnrbihPxa6C2USA0px58WKXwZ5zx2cOe+yQq+CF9Vy8lfonYtmMr/Syr59jSsD1NA7jEWHU2ujf/CeROx+2dwlYyGv4fWYzzTUv0WB/2ofgyiqmRo0lzffK/UOpNvIGAVIg8g6Xdd7yIOEDF+3O4CLgSQWHiR6eB134Py9m/TYODTL/7M89Vf8C2/WJwW+Q3bOGuHxJlF3enM4="
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.6
