language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server

matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: required

script:
- make install-minimal
- make test-minimal
- make install
- make lint
- make test
- ./tests/check_tag.py
- ls -lha
- pip freeze

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: pypi
  user: samuelcolvin
  password:
    secure: "bOPzY9+FmNtYIq8+7GT6/CiFgDi8JqG+/mC/AEaVthi3FAOaB9JpoZ+LuKbN9+/oMw+X8bZ9KkdSFR85LihH+AvccOXDi1x6alQpgbLD2GmP6AMaaa4EqFdVwt7o6i2WimRzni2Fe4by/S2b+Z745MgrHcG2Dge+hEEUvpQQQv5+c8LFgZCaVZGlFYivzU7YuoGW5UXgfCoAxHs/B7tnKMaVLkaVQaA9WY69MssfpvLxtU4CXrztc88uczwBzEnxmVYAxVvxWkd4Gdh1f3C1ciNASDKyLQl00oo412nc3T7O0AQ39IrhaLBII1BMurRKwn9DdEAlwX/6n4UPn3wyfX/RzLrcZeTsLclq2K2EUXwuZXpUGZWjIJedQnk0rQkulLifJuPV3y5AcI756oBwgIkkVVoaoos9U5sqPGwPDtzGMFrBA25zH3T6+CtgszHJtdIM9tdk6M9+Ilx8w9aMALuPX9KxuW0oYs0SlWnsel1/nrQ0dyZ3h9lOHvlTgjzgykQgmk98iN2etBa6vvsa1OTvHFxO3Bzt+ErLF+VsXRiZMb4OsD6yg54X/vqG8EnsR4k8zLQObZGo2MbFWztAEtsp8RFXWSR69BDCQqZAlrURYiA3mRwb9oNPOM8QJ1uitvxgLIhSqoh33FVc4qIvT0LUGRt8hIdk6dXJxjUp4s4="
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.6
